name: Keybox Check Action

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  check_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests cryptography

    - name: Check
      run: python checkKB.py files

    - name: Package Zip
      run: |
        cd files
        zip -r ../keybox.zip ./*

    - name: Update keybox.zip
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add keybox.zip
        git commit -m "Update keybox.zip"
        git push
